name: Build & Deploy mtk5586hal1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -t mtk5586hal1 .
      
      - name: Run Docker Container to verify
        run: |
          docker run --rm mtk5586hal1
      
      - name: Login to Docker Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: myjfrogrepo.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASS }}
      
      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag mtk5586hal1 myjfrogrepo.jfrog.io/docker-local/mtk5586hal1:latest
          docker push myjfrogrepo.jfrog.io/docker-local/mtk5586hal1:latest
